{% set name = "pyomicron" %}
{% set version = "2.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27ae6b981dae8c9940774daa01a046c7eeae5aacfb01964bbde875ba3656ba67

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - omicron-hdf5-merge = omicron.cli.hdf5_merge:main
    - omicron-show = omicron.cli.show:main
    - omicron-process = omicron.cli.process:main
    - omicron-root-merge = omicron.cli.root_merge:main
    - omicron-status = omicron.cli.status:main
    - omicron-archive = omicron.cli.archive:main
    - omicron-merge-with-gaps = omicron.cli.merge_with_gaps:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - dqsegdb2 >=1.2.0
    - gwdatafind
    - gwpy >=2.0.0
    - h5py
    - igwn-auth-utils >=0.3.0
    - ligo-segments
    - lscsoft-glue >=1.60.0
    - markuppy
    - numpy
    - omicron >=2.3.12
    - pycondor
    - python >={{ python_min }}
    - python-htcondor
    - python-ldas-tools-framecpp
    - python-ligo-lw >=1.4.0
    - root_base

test:
  requires:
    - pip
    - pytest >=3.9.1
    - python {{ python_min }}
  imports:
    - omicron
    - omicron.cli
    - omicron.condor
    - omicron.const
    - omicron.data
    - omicron.io
    - omicron.log
    - omicron.nagios
    - omicron.parameters
    - omicron.segments
    - omicron.utils
  commands:
    # check dependencies
    - python -m pip check
    - python -m pip show pyomicron
    # run unit tests
    - python -m pytest -ra --pyargs omicron
    # check that scripts were built
    - omicron-hdf5-merge --help
    - omicron-show --help
    - omicron-process --help
    - omicron-root-merge --help
    - omicron-status --help
    - omicron-archive --help
    - omicron-merge-with-gaps --help

about:
  home: https://github.com/gwpy/pyomicron
  dev_url: https://github.com/gwpy/pyomicron.git
  doc_url: https://pyomicron.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python utilities and extensions for the Omicron (C++) GW event trigger generator
  description: |
    This package provides a set of python utilities for gravitational-wave
    detector characterisation and data quality. It is intended for use by
    the International Gravitational Wave Network (IGWN) of ground-based
    detectors, along with the Omicron (C++) package.

extra:
  recipe-maintainers:
    - areeda
    - duncanmmacleod
    - eagoetz
    - robertbruntz
